import type { RecentJob } from "@/types";

export const RECENT_JOBS: RecentJob[] = [
  {
    id: "job-1",
    image: "/images/jobs/job-4.jpg",
    alt: "Washer repair in Middleburg Heights",
    service: "Washer Repair",
    location: "Middleburg Heights",
    date: "01.02.2026",
    problem: "Water leaks from the bottom of the door",
  },
  {
    id: "job-2",
    image: "/images/jobs/job-5.jpg",
    alt: "Refrigerator repair in Cleveland",
    service: "Refrigerator Repair",
    location: "Cleveland",
    date: "03.02.2026",
    problem: "Not cooling, compressor running constantly",
  },
  {
    id: "job-3",
    image: "/images/jobs/job-4.jpg",
    alt: "Dryer repair in Parma",
    service: "Dryer Repair",
    location: "Parma",
    date: "07.02.2026",
    problem: "No heat, clothes not drying",
  },
  {
    id: "job-4",
    image: "/images/jobs/job-5.jpg",
    alt: "Dishwasher repair in Strongsville",
    service: "Dishwasher Repair",
    location: "Strongsville",
    date: "10.02.2026",
    problem: "Standing water after every cycle",
  },
  {
    id: "job-5",
    image: "/images/jobs/job-4.jpg",
    alt: "Freezer repair in Westlake",
    service: "Freezer Repair",
    location: "Westlake",
    date: "14.02.2026",
    problem: "Heavy frost buildup inside",
  },
  {
    id: "job-6",
    image: "/images/jobs/job-5.jpg",
    alt: "Oven repair in Brunswick",
    service: "Oven & Stove Repair",
    location: "Brunswick",
    date: "18.02.2026",
    problem: "Oven not reaching set temperature",
  },
  {
    id: "job-7",
    image: "/images/jobs/job-4.jpg",
    alt: "Ice maker repair in Parma",
    service: "Ice Maker Repair",
    location: "Parma",
    date: "21.02.2026",
    problem: "Ice maker not producing ice",
  },
  {
    id: "job-8",
    image: "/images/jobs/job-5.jpg",
    alt: "Kitchen appliance repair in Cleveland",
    service: "Kitchen Appliance Repair",
    location: "Cleveland",
    date: "25.02.2026",
    problem: "Microwave not heating food",
  },
  {
    id: "job-9",
    image: "/images/jobs/job-4.jpg",
    alt: "Washer repair in Berea",
    service: "Washer Repair",
    location: "Berea",
    date: "01.03.2026",
    problem: "Washing machine not spinning",
  },
  {
    id: "job-10",
    image: "/images/jobs/job-5.jpg",
    alt: "Refrigerator repair in Parma",
    service: "Refrigerator Repair",
    location: "Parma",
    date: "04.03.2026",
    problem: "Ice maker leaking water inside fridge",
  },
  {
    id: "job-11",
    image: "/images/jobs/job-4.jpg",
    alt: "Dryer repair in Middleburg Heights",
    service: "Dryer Repair",
    location: "Middleburg Heights",
    date: "08.03.2026",
    problem: "Dryer making loud banging noise",
  },
  {
    id: "job-12",
    image: "/images/jobs/job-5.jpg",
    alt: "Dishwasher repair in Westlake",
    service: "Dishwasher Repair",
    location: "Westlake",
    date: "12.03.2026",
    problem: "Dishes coming out dirty after full cycle",
  },
];
