import type { RecentJob } from "@/types";

export const RECENT_JOBS: RecentJob[] = [
  {
    id: "job-1",
    image: "/images/jobs/job-4.jpg",
    alt: "Washer repair in Middleburg Heights",
    service: "Washer Repair",
    location: "Middleburg Heights",
    date: "01.02.2026",
    problem: "Water leaks from the bottom of the door",
    intro: [
      "Our technician inspected the door boot seal and found a tear causing water to leak during the spin cycle. The damaged seal was replaced with a genuine OEM part.",
      "After the repair, we ran a full test cycle to confirm the leak was resolved and the washer was operating correctly.",
    ],
    commonProblems: [
      "Washer not draining",
      "Washing machine not spinning",
      "Water leakage issues",
      "Loud or unusual noises",
      "Washer won't start",
      "Door or lid lock problems",
      "Error codes and electrical issues",
      "Slow filling or water supply problems",
    ],
    whyChoosePoints: [
      "Experienced and certified technicians",
      "Same-day and emergency repair options",
      "Transparent pricing with no hidden fees",
      "Repairs for all major brands",
      "Quality replacement parts",
      "Friendly and professional customer support",
    ],
    closingHeading: "Fast & Reliable Washer Repair",
    closingText: [
      "We understand how important a working washing machine is for your home. That's why we focus on quick response times and long-lasting repair solutions that help prevent future problems.",
      "Our goal is simple: get your washer running smoothly again with minimal stress and downtime.",
      "Don't let a faulty washing machine slow you down. Contact our team today to book a professional washer repair service and get your appliance back in perfect working condition.",
    ],
  },
  {
    id: "job-2",
    image: "/images/jobs/job-5.jpg",
    alt: "Refrigerator repair in Cleveland",
    service: "Refrigerator Repair",
    location: "Cleveland",
    date: "03.02.2026",
    problem: "Not cooling, compressor running constantly",
    intro: [
      "Our technician diagnosed the issue and found a faulty start relay causing the compressor to run without reaching proper cooling temperature. The relay was replaced on the same visit.",
      "We verified the refrigerator reached the correct temperature and the compressor was cycling normally before leaving.",
    ],
    commonProblems: [
      "Refrigerator not cooling properly",
      "Compressor running constantly",
      "Ice maker not working",
      "Water leaking inside or outside",
      "Unusual noises from the unit",
      "Freezer frosting over",
      "Temperature fluctuations",
      "Door seals not closing properly",
    ],
    whyChoosePoints: [
      "Factory-trained refrigerator repair technicians",
      "Same-day service available",
      "Upfront, transparent pricing",
      "All major brands serviced",
      "OEM and quality replacement parts",
      "90-day parts and labor warranty",
    ],
    closingHeading: "Fast & Reliable Refrigerator Repair",
    closingText: [
      "A malfunctioning refrigerator can lead to food spoilage and costly waste. Our technicians arrive equipped with the most common parts to resolve most issues on the first visit.",
      "We service all major refrigerator brands including Samsung, LG, Whirlpool, GE, and more.",
      "Call us today for a same-day refrigerator repair appointment in Cleveland and surrounding areas.",
    ],
  },
  {
    id: "job-3",
    image: "/images/jobs/job-4.jpg",
    alt: "Dryer repair in Parma",
    service: "Dryer Repair",
    location: "Parma",
    date: "07.02.2026",
    problem: "No heat, clothes not drying",
    intro: [
      "The technician tested the heating element and found it had burned out. A new heating element was installed along with a thermal fuse replacement to prevent recurrence.",
      "The dryer was tested through a full drying cycle and heat output was confirmed to be within manufacturer specifications.",
    ],
    commonProblems: [
      "Dryer producing no heat",
      "Clothes not drying fully",
      "Dryer taking too long to dry",
      "Dryer making loud noises",
      "Dryer not starting",
      "Overheating or shutting off",
      "Drum not spinning",
      "Error codes displayed",
    ],
    whyChoosePoints: [
      "Certified dryer repair specialists",
      "Fast turnaround — most repairs same day",
      "No hidden charges or service fees",
      "Gas and electric dryer repairs",
      "All major brands covered",
      "90-day warranty on all repairs",
    ],
    closingHeading: "Fast & Reliable Dryer Repair",
    closingText: [
      "A broken dryer is more than an inconvenience — it can disrupt your entire household routine. Our technicians are trained to diagnose and fix dryer issues quickly and efficiently.",
      "Whether it's a heating element, drum belt, or electronic control board, we carry common parts to fix most dryers in a single visit.",
      "Schedule your dryer repair in Parma today and get back to your routine.",
    ],
  },
  {
    id: "job-4",
    image: "/images/jobs/job-5.jpg",
    alt: "Dishwasher repair in Strongsville",
    service: "Dishwasher Repair",
    location: "Strongsville",
    date: "10.02.2026",
    problem: "Standing water after every cycle",
    intro: [
      "Our technician inspected the drain system and found a foreign object lodged in the drain pump, which caused the pump motor to burn out. The blockage was removed and the drain pump was replaced with a new OEM part.",
      "A full test cycle confirmed the dishwasher drains properly and all wash functions are operating correctly.",
    ],
    commonProblems: [
      "Dishwasher not draining",
      "Dishes not getting clean",
      "Water leaking onto floor",
      "Dishwasher not starting",
      "Unusual noises during cycle",
      "Door latch not closing",
      "Detergent dispenser not opening",
      "Error codes on display",
    ],
    whyChoosePoints: [
      "Experienced dishwasher repair technicians",
      "Same-day service in Strongsville",
      "Honest, upfront pricing",
      "All major brands serviced",
      "Genuine replacement parts used",
      "90-day parts and labor warranty",
    ],
    closingHeading: "Fast & Reliable Dishwasher Repair",
    closingText: [
      "A dishwasher that won't drain or clean properly makes kitchen cleanup a hassle. Our team provides fast, affordable dishwasher repair so you can get back to a clean kitchen.",
      "We service all major brands including Bosch, KitchenAid, Whirlpool, GE, and Samsung.",
      "Book your dishwasher repair in Strongsville today.",
    ],
  },
  {
    id: "job-5",
    image: "/images/jobs/job-4.jpg",
    alt: "Freezer repair in Westlake",
    service: "Freezer Repair",
    location: "Westlake",
    date: "14.02.2026",
    problem: "Heavy frost buildup inside",
    intro: [
      "The technician tested the defrost system and found a failed defrost heater causing excessive frost buildup. The heater and thermostat were both replaced to restore proper defrost cycles.",
      "After the repair, the freezer was tested over several hours to confirm the defrost system was operating correctly and frost buildup had stopped.",
    ],
    commonProblems: [
      "Excessive frost or ice buildup",
      "Freezer not maintaining temperature",
      "Strange noises from the unit",
      "Freezer door not sealing properly",
      "Water pooling inside or underneath",
      "Freezer running constantly",
      "Ice maker not working",
      "Freezer not turning on",
    ],
    whyChoosePoints: [
      "Certified freezer repair technicians",
      "Same-day service available",
      "Transparent, upfront pricing",
      "All major brands repaired",
      "Quality OEM replacement parts",
      "90-day warranty on all work",
    ],
    closingHeading: "Fast & Reliable Freezer Repair",
    closingText: [
      "Frost buildup and temperature issues can quickly lead to food spoilage and costly losses. Our technicians identify the root cause and fix it right the first time.",
      "We repair all freezer types including chest freezers, upright freezers, and combination refrigerator-freezer units.",
      "Call us today for freezer repair service in Westlake.",
    ],
  },
  {
    id: "job-6",
    image: "/images/jobs/job-5.jpg",
    alt: "Oven repair in Brunswick",
    service: "Oven & Stove Repair",
    location: "Brunswick",
    date: "18.02.2026",
    problem: "Oven not reaching set temperature",
    intro: [
      "Our technician tested the bake element and oven temperature sensor and found the sensor was reading incorrectly, causing the oven to underheat. The sensor was replaced and temperature calibration was verified.",
      "After replacement, the oven was tested at multiple temperature settings to confirm accurate heating.",
    ],
    commonProblems: [
      "Oven not heating or underheating",
      "Burners not igniting",
      "Oven temperature inaccurate",
      "Self-cleaning function not working",
      "Oven door not closing properly",
      "Control panel errors",
      "Gas smell when using stove",
      "Broiler not working",
    ],
    whyChoosePoints: [
      "Certified gas and electric oven technicians",
      "Same-day repair appointments",
      "No surprise fees — upfront quotes",
      "All major oven and range brands",
      "OEM parts for lasting repairs",
      "90-day parts and labor warranty",
    ],
    closingHeading: "Fast & Reliable Oven & Stove Repair",
    closingText: [
      "An oven that won't heat properly can disrupt meal planning and daily life. Our technicians are trained to diagnose and fix both gas and electric ovens efficiently.",
      "We service all major brands including GE, Whirlpool, Samsung, LG, Bosch, and more.",
      "Schedule your oven repair in Brunswick today and have your kitchen back to full operation.",
    ],
  },
  {
    id: "job-7",
    image: "/images/jobs/job-4.jpg",
    alt: "Ice maker repair in Parma",
    service: "Ice Maker Repair",
    location: "Parma",
    date: "21.02.2026",
    problem: "Ice maker not producing ice",
    intro: [
      "The technician found the water inlet valve was clogged and not allowing water to flow into the ice maker. The valve was replaced and water flow was restored.",
      "After the repair, we confirmed the ice maker completed a full freeze and harvest cycle before leaving.",
    ],
    commonProblems: [
      "Ice maker not producing ice",
      "Ice maker leaking water",
      "Small or misshapen ice cubes",
      "Ice has bad taste or odor",
      "Ice maker making loud noises",
      "Ice dispenser not working",
      "Ice maker freezing up",
      "Water inlet valve issues",
    ],
    whyChoosePoints: [
      "Experienced ice maker repair technicians",
      "Fast, same-day appointments",
      "Transparent pricing — no surprises",
      "All refrigerator brands serviced",
      "Genuine replacement parts",
      "90-day warranty on all repairs",
    ],
    closingHeading: "Fast & Reliable Ice Maker Repair",
    closingText: [
      "A broken ice maker is frustrating, especially in warmer months. Our technicians diagnose and fix ice maker issues quickly so you're never without ice for long.",
      "We repair built-in and freestanding ice makers for all major brands.",
      "Contact us today for ice maker repair in Parma.",
    ],
  },
  {
    id: "job-8",
    image: "/images/jobs/job-5.jpg",
    alt: "Kitchen appliance repair in Cleveland",
    service: "Kitchen Appliance Repair",
    location: "Cleveland",
    date: "25.02.2026",
    problem: "Microwave not heating food",
    intro: [
      "Our technician tested the magnetron and high-voltage diode and found the diode had failed, preventing the magnetron from generating heat. The diode was replaced and the microwave was tested.",
      "The unit was confirmed to heat food evenly and safely before the job was completed.",
    ],
    commonProblems: [
      "Microwave not heating",
      "Turntable not rotating",
      "Microwave sparking inside",
      "Door not closing properly",
      "Control panel not responding",
      "Unusual noises during operation",
      "Microwave shutting off unexpectedly",
      "Display not working",
    ],
    whyChoosePoints: [
      "Certified kitchen appliance technicians",
      "Same-day service in Cleveland",
      "Upfront pricing with no hidden fees",
      "All major appliance brands covered",
      "Safe, quality replacement parts",
      "90-day warranty on all repairs",
    ],
    closingHeading: "Fast & Reliable Kitchen Appliance Repair",
    closingText: [
      "Kitchen appliances are essential to your daily routine. Our technicians provide fast, professional repairs to keep your kitchen running smoothly.",
      "We service microwaves, range hoods, and other kitchen appliances for all major brands.",
      "Book your kitchen appliance repair in Cleveland today.",
    ],
  },
  {
    id: "job-9",
    image: "/images/jobs/job-4.jpg",
    alt: "Washer repair in Berea",
    service: "Washer Repair",
    location: "Berea",
    date: "01.03.2026",
    problem: "Washing machine not spinning",
    intro: [
      "The technician found a worn drive belt and a faulty lid switch preventing the washer from entering the spin cycle. Both components were replaced during the same visit.",
      "After the repair, the washer was tested through a complete wash and spin cycle with no issues.",
    ],
    commonProblems: [
      "Washer not spinning",
      "Washer not draining",
      "Water leakage issues",
      "Loud or unusual noises",
      "Washer won't start",
      "Unbalanced loads causing errors",
      "Error codes on display",
      "Slow filling or water supply problems",
    ],
    whyChoosePoints: [
      "Certified washer repair technicians",
      "Same-day and emergency service",
      "Transparent, no-surprise pricing",
      "All major brands repaired",
      "Genuine OEM replacement parts",
      "90-day parts and labor warranty",
    ],
    closingHeading: "Fast & Reliable Washer Repair",
    closingText: [
      "A washer that won't spin leaves clothes soaked and your day disrupted. We diagnose and fix washer problems efficiently, usually completing repairs in a single visit.",
      "We service all major washer brands including LG, Samsung, Whirlpool, GE, and Maytag.",
      "Schedule your washer repair in Berea today.",
    ],
  },
  {
    id: "job-10",
    image: "/images/jobs/job-5.jpg",
    alt: "Refrigerator repair in Parma",
    service: "Refrigerator Repair",
    location: "Parma",
    date: "04.03.2026",
    problem: "Ice maker leaking water inside fridge",
    intro: [
      "Our technician traced the leak to a cracked water fill tube and a worn door gasket on the ice maker compartment. Both were replaced using OEM parts.",
      "The refrigerator was monitored through several ice-making cycles to confirm no further leaking.",
    ],
    commonProblems: [
      "Ice maker leaking water",
      "Refrigerator not cooling",
      "Unusual noises from the unit",
      "Ice maker not producing ice",
      "Water pooling inside the fridge",
      "Frost buildup in freezer",
      "Door seals not closing properly",
      "Temperature control not working",
    ],
    whyChoosePoints: [
      "Factory-trained refrigerator technicians",
      "Same-day appointments available",
      "Honest, upfront pricing",
      "All major brands serviced",
      "Genuine replacement parts",
      "90-day warranty on all work",
    ],
    closingHeading: "Fast & Reliable Refrigerator Repair",
    closingText: [
      "Water leaks inside your refrigerator can damage food, cause mold, and lead to bigger problems over time. Our technicians identify and fix leaks quickly.",
      "We service all major refrigerator brands across Parma and surrounding areas.",
      "Contact us today to book a same-day refrigerator repair appointment.",
    ],
  },
  {
    id: "job-11",
    image: "/images/jobs/job-4.jpg",
    alt: "Dryer repair in Middleburg Heights",
    service: "Dryer Repair",
    location: "Middleburg Heights",
    date: "08.03.2026",
    problem: "Dryer making loud banging noise",
    intro: [
      "The technician identified worn drum support rollers and a damaged drum glide as the source of the loud banging. Both were replaced and the drum was rebalanced.",
      "After the repair, the dryer ran quietly through a full cycle with no vibration or noise.",
    ],
    commonProblems: [
      "Loud banging or thumping during cycle",
      "Dryer not heating",
      "Clothes taking too long to dry",
      "Dryer not starting",
      "Drum not spinning",
      "Dryer overheating and shutting off",
      "Burning smell during operation",
      "Error codes on display",
    ],
    whyChoosePoints: [
      "Certified dryer repair specialists",
      "Same-day service available",
      "No hidden fees — upfront quotes",
      "Gas and electric dryer repairs",
      "All major brands covered",
      "90-day warranty on repairs",
    ],
    closingHeading: "Fast & Reliable Dryer Repair",
    closingText: [
      "Loud noises from your dryer are usually a sign of worn mechanical parts that will worsen over time. Early repairs save you from more expensive breakdowns.",
      "Our technicians arrive with common parts on hand to fix most dryers in a single visit.",
      "Book your dryer repair in Middleburg Heights today.",
    ],
  },
  {
    id: "job-12",
    image: "/images/jobs/job-5.jpg",
    alt: "Dishwasher repair in Westlake",
    service: "Dishwasher Repair",
    location: "Westlake",
    date: "12.03.2026",
    problem: "Dishes coming out dirty after full cycle",
    intro: [
      "Our technician found a clogged spray arm and a failing wash pump reducing water pressure during the cycle. The spray arms were cleaned and the wash pump was replaced.",
      "After the repair, the dishwasher was run through a full cycle and dishes came out clean with no residue.",
    ],
    commonProblems: [
      "Dishes not getting clean",
      "Dishwasher not draining",
      "Water leaking onto floor",
      "Spray arms clogged or broken",
      "Dishwasher not starting",
      "Detergent dispenser not opening",
      "Unusual noises during cycle",
      "Error codes on display",
    ],
    whyChoosePoints: [
      "Experienced dishwasher repair technicians",
      "Fast, same-day service",
      "Transparent pricing — no surprises",
      "All major brands serviced",
      "Genuine replacement parts",
      "90-day parts and labor warranty",
    ],
    closingHeading: "Fast & Reliable Dishwasher Repair",
    closingText: [
      "Dirty dishes after a full wash cycle waste your time and water. Our technicians diagnose the root cause and fix it right the first time.",
      "We repair all major dishwasher brands including Bosch, KitchenAid, Whirlpool, GE, and Samsung.",
      "Schedule your dishwasher repair in Westlake today.",
    ],
  },
];
