import type { RecentJob } from "@/types";

export const RECENT_JOBS: RecentJob[] = [
  {
    id: "job-1",
    slug: "washer-repair-cleveland-heights",
    image: "/images/recent-jobs/job-1/cover.jpg",
    alt: "Washer repair in Cleveland Heights",
    service: "Washer Repair",
    location: "Cleveland Heights",
    date: "08.07.2026",
    problem: "Water leaking during the wash cycle",
    intro: [
      "We recently completed a washer repair in Cleveland Heights after the homeowner noticed water leaking during the wash cycle. At first, it appeared to be a straightforward leak, but our inspection quickly showed there was more to the story.",
      "We found that the pressure hose had come loose from the outer tub, allowing water to leak into the bottom of the washer. Rather than simply reconnecting the hose and calling it done, we wanted to understand what caused it to come loose in the first place.",
      "During the spin cycle, the washer was shaking far more than normal. A closer inspection revealed that the worn shock absorbers were no longer keeping the tub stable. The excessive movement had gradually worked the pressure hose loose, which ultimately caused the leak.",
      "We replaced the worn shock absorbers, properly secured the pressure hose, and ran several complete test cycles. The washer now spins smoothly without excessive vibration, and the leak has been fully resolved.",
    ],
    commonProblems: [
      "Washer not draining",
      "Washing machine not spinning",
      "Water leakage issues",
      "Loud or unusual noises",
      "Washer won't start",
      "Door or lid lock problems",
      "Error codes and electrical issues",
      "Slow filling or water supply problems",
    ],
    whyChoosePoints: [
      "Experienced and certified technicians",
      "Same-day and emergency repair options",
      "Transparent pricing with no hidden fees",
      "Repairs for all major brands",
      "Quality replacement parts",
      "Friendly and professional customer support",
    ],
    closingHeading: "Fast & Reliable Appliance Repair",
    closingText: [
      "We understand how important a working washing machine is for your home. That's why we focus on quick response times and long-lasting repair solutions that help prevent future problems.",
      "Our goal is simple: get your washer running smoothly again with minimal stress and downtime.",
      "Don't let a faulty washing machine slow you down. Contact our team today to book a professional washer repair service and get your appliance back in perfect working condition.",
    ],
  },
  {
    id: "job-2",
    slug: "dryer-repair-cleveland-heights",
    image: "/images/recent-jobs/job-2/cover.jpg",
    alt: "Dryer repair in Cleveland Heights",
    service: "Dryer Repair",
    location: "Cleveland Heights",
    date: "19.06.2026",
    problem: "No heat and loud grinding noise",
    intro: [
      "A homeowner in Cleveland Heights, Ohio contacted us because their gas dryer stopped heating and started making a loud grinding noise.",
      "During our diagnosis, we found that the blower wheel was badly damaged, restricting airflow through the dryer. Poor airflow was the reason the dryer wasn't heating properly, and it was also causing the grinding noise.",
      "We replaced the damaged blower wheel, restored proper airflow, and tested the dryer through multiple cycles. The dryer is now heating properly, running quietly, and ready to use again.",
    ],
    commonProblems: [
      "Dryer not heating",
      "Clothes taking too long to dry",
      "Dryer won't start",
      "Loud or unusual noises",
      "Drum not turning",
      "Overheating issues",
      "Error codes and electrical problems",
    ],
    whyChoosePoints: [
      "Same-day dryer repair service",
      "Certified technicians for all brands",
      "Transparent, upfront pricing",
      "Genuine manufacturer-approved parts",
      "180-day parts & labor warranty",
    ],
    closingHeading: "Get Your Dryer Running Again",
    closingText: [
      "Don't let a broken dryer disrupt your household. Our experienced team provides fast, affordable dryer repairs in Cleveland and Parma.",
      "Contact us today to schedule your same-day dryer repair service.",
    ],
  },
  {
    id: "job-3",
    slug: "refrigerator-repair-brecksville",
    image: "/images/recent-jobs/job-3/cover.jpg",
    alt: "Refrigerator repair in Brecksville",
    service: "Refrigerator Repair",
    location: "Brecksville",
    date: "02.07.2026",
    problem: "Freezer section not cooling",
    intro: [
      "One of our recent service calls in Brecksville involved a Sub-Zero refrigerator with an unusual cooling problem. The refrigerator section was staying cold, but the freezer section had stopped cooling completely.",
      "After a thorough diagnosis, we found that the freezer compressor had failed. Once the faulty compressor was replaced, we tested the sealed system and monitored the temperatures to make sure everything was operating correctly.",
      "With the new compressor in place, the freezer was cooling properly again, and the refrigerator was ready to serve its owner for many more years.",
    ],
    commonProblems: [
      "Refrigerator not cooling",
      "Freezer not freezing",
      "Ice maker not working",
      "Water leaking inside or under fridge",
      "Loud compressor or fan noises",
      "Temperature fluctuations",
      "Door seal and gasket issues",
    ],
    whyChoosePoints: [
      "Fast same-day refrigerator repair",
      "All major brands serviced",
      "Transparent pricing, no surprises",
      "180-day warranty on all repairs",
      "Locally trusted in Cleveland & Parma",
    ],
    closingHeading: "Keep Your Food Fresh",
    closingText: [
      "A refrigerator breakdown is urgent. Our team responds quickly to get your fridge back to optimal temperature as soon as possible.",
      "Call us today for fast, reliable refrigerator repair in Cleveland and Parma.",
    ],
  },
  {
    id: "job-4",
    slug: "oven-repair-parma",
    image: "/images/recent-jobs/job-4/cover.jpg",
    alt: "Oven repair in Parma",
    service: "Oven Repair",
    location: "Parma",
    date: "14.07.2026",
    problem: "Oven not heating",
    intro: [
      "A customer in Parma contacted us because their oven was taking much longer than usual to preheat and eventually stopped heating altogether.",
      "During the diagnosis, we found that the bake igniter was no longer reaching the proper resistance, preventing it from drawing enough current to open the gas valve. As a result, the gas never ignited, and the oven could not produce heat.",
      "We replaced the faulty bake igniter, tested the ignition system, and confirmed that the oven was preheating and heating normally again.",
    ],
    commonProblems: [
      "Oven not heating to correct temperature",
      "Oven door not closing properly",
      "Control panel errors",
      "Uneven baking or cooking",
      "Self-clean cycle problems",
      "Heating element failure",
      "Igniter not working",
    ],
    whyChoosePoints: [
      "Gas and electric oven specialists",
      "Same-day appointments available",
      "Certified and insured technicians",
      "Upfront pricing before any work begins",
      "180-day parts & labor warranty",
    ],
    closingHeading: "Get Your Oven Back in Action",
    closingText: [
      "Don't let a broken oven disrupt your meals. Our team provides fast, professional oven repairs across Cleveland and Parma.",
      "Schedule your repair today and get your kitchen back in working order.",
    ],
  },
  {
    id: "job-5",
    slug: "washer-repair-westlake",
    image: "/images/recent-jobs/job-5/cover.jpg",
    alt: "Washer repair in Westlake",
    service: "Washer Repair",
    location: "Westlake",
    date: "25.06.2026",
    problem: "Not filling with water",
    intro: [
      "A Maytag washer in Westlake stopped filling with water, preventing the wash cycle from starting.",
      "After checking the water supply and diagnosing the machine, we found that the water inlet valve had failed and was no longer allowing water into the washer.",
      "We replaced the faulty valve and ran several test cycles to make sure the washer was filling properly and operating as it should. The repair restored normal water flow, and the machine was ready to use again.",
    ],
    commonProblems: [
      "Washer not draining",
      "Washing machine not spinning",
      "Water leakage issues",
      "Loud or unusual noises",
      "Washer won't start",
      "Door or lid lock problems",
      "Error codes and electrical issues",
      "Slow filling or water supply problems",
    ],
    whyChoosePoints: [
      "Experienced and certified technicians",
      "Same-day and emergency repair options",
      "Transparent pricing with no hidden fees",
      "Repairs for all major brands",
      "Quality replacement parts",
      "Friendly and professional customer support",
    ],
    closingHeading: "Fast & Reliable Appliance Repair",
    closingText: [
      "We understand how important a working washing machine is for your home. That's why we focus on quick response times and long-lasting repair solutions that help prevent future problems.",
      "Our goal is simple: get your washer running smoothly again with minimal stress and downtime.",
      "Don't let a faulty washing machine slow you down. Contact our team today to book a professional washer repair service and get your appliance back in perfect working condition.",
    ],
  },
  {
    id: "job-6",
    slug: "dishwasher-repair-avon-lake",
    image: "/images/recent-jobs/job-6/cover.jpg",
    alt: "Dishwasher repair in Avon Lake",
    service: "Dishwasher Repair",
    location: "Avon Lake",
    date: "21.07.2026",
    problem: "Not draining after cycle",
    intro: [
      "A customer in Avon Lake reported that their dishwasher was not draining properly.",
      "After inspecting the unit, we found that the drain pump had failed.",
      "We replaced the faulty drain pump, tested the dishwasher to make sure it was draining correctly, and confirmed everything was working as expected. The repair was completed successfully, and the dishwasher is now operating normally.",
    ],
    commonProblems: [
      "Dishwasher not cleaning dishes",
      "Standing water after cycle",
      "Dishwasher won't start",
      "Door latch problems",
      "Unusual noises during operation",
      "Water leaking onto floor",
      "Error codes on control panel",
    ],
    whyChoosePoints: [
      "Same-day dishwasher repair",
      "Certified for all major brands",
      "Upfront flat-rate pricing",
      "Genuine replacement parts",
      "180-day parts & labor warranty",
    ],
    closingHeading: "Fast Dishwasher Repair You Can Trust",
    closingText: [
      "Our team provides reliable dishwasher repairs in Cleveland and Parma with minimal disruption to your daily routine.",
      "Book your repair today and have your dishwasher working like new.",
    ],
  },
];
